---
title: "uas R"
author: "Kelompok 1"
date: "2023-12-19"
output: html_document
---

## IMPORT LIBRARY
```{r}
library(dplyr)
library(ggplot2)
library(caret)
library(tidyverse)
library(psych) #Untuk melihat data normal
library(moments) #Untuk menghitung Pearson Kurtosis, Geary Skewness
library(outliers) #Untuk mendeteksi outliers
library(Metrics)
library(randomForest)
library(e1071)
library(janitor)
library(shiny)
```


## LOADING DATASET
```{r}
admisi = read.csv('admisi.csv', header = TRUE, sep = ";")
profiling = read.csv('profiling.csv', header = TRUE, sep = ";")

# Menggabungkan dataset berdasarkan kolom ID
newdata = merge(profiling, admisi, by = "ID")
newdata
```


## DATA PREPROCESSING 1: HANDLING MISSING VALUE
```{r}

# Menghitung modus
modus_jenkel = names(sort(table(newdata$JENIS_KEL), decreasing = TRUE)[1])
modus_riset = names(sort(table(newdata$RISET), decreasing = TRUE)[1])
modus_lulus = names(sort(table(newdata$LULUS), decreasing = TRUE)[1])

# Mengganti nilai NA dengan modus
newdata$JENIS_KEL[is.na(newdata$JENIS_KEL)] = modus_jenkel
newdata$RISET[is.na(newdata$RISET)] = modus_riset
newdata$LULUS[is.na(newdata$LULUS)] = modus_lulus

# Transformasi faktor
newdata$JENIS_KEL = as.factor(newdata$JENIS_KEL)
newdata$LULUS = factor(newdata$LULUS, levels = c(1, 0), labels = c('Lulus', 'Tidak Lulus'))
newdata$RISET = as.factor(newdata$RISET)

# Mengganti koma (,) dengan titik (.) pada kolom "IPK"
newdata$IPK = gsub(",", ".", newdata$IPK)
newdata$MOT_LETTER = gsub(",", ".", newdata$MOT_LETTER)
newdata$REKOM_LETTER <- gsub(",", ".", newdata$REKOM_LETTER)

# Mengganti nilai NA pada nilai non-numerik
newdata$IPK = as.numeric(newdata$IPK)
newdata$MOT_LETTER = as.numeric(newdata$MOT_LETTER)
newdata$REKOM_LETTER = as.numeric(newdata$REKOM_LETTER)

# Menghitung mean
mean_rank = mean(newdata$Ranking_Uni_Asal, na.rm = TRUE)
mean_motl = mean(newdata$MOT_LETTER, na.rm = TRUE)
mean_koml = mean(newdata$REKOM_LETTER, na.rm = TRUE)

# Mengganti nilai NA dengan mean
newdata$Ranking_Uni_Asal[is.na(newdata$Ranking_Uni_Asal)] = mean_rank
newdata$MOT_LETTER[is.na(newdata$MOT_LETTER)] = mean_motl
newdata$REKOM_LETTER[is.na(newdata$REKOM_LETTER)] = mean_koml

str(newdata)

```


## DATA PREPROCESSING 2: HANDLING DUPLICATED DATA
```{R}

# Cek Data Duplikat
cek = get_dupes(newdata)
cek

# Mempertahankan satu baris dari setiap kelompok duplikat
newdata_unique = distinct(newdata, .keep_all = TRUE)

```


## DATA PREPROCESSING 3: HANDLING OUTLIER

```{r}

# Loop untuk menampilkan boxplot satu per satu untuk variabel numerik
for (col in names(newdata_unique)) {
  if (is.numeric(newdata_unique[[col]])) {
    boxplot(newdata_unique[[col]], main = col)
  }
}

# Menghapus Outliers
IQR_ipk = IQR(newdata_unique$IPK)
upfen_ipk = quantile(newdata_unique$IPK, 0.75) + 1.5 * IQR_ipk

IQR_koml = IQR(newdata_unique$REKOM_LETTER)
lowfen_koml = quantile(newdata_unique$REKOM_LETTER, 0.25) - 1.5 * IQR_koml

clean_newdata = subset(newdata_unique, newdata_unique$IPK <= upfen_ipk 
                       & newdata_unique$REKOM_LETTER >= lowfen_koml)

# Mengecek apakah masih terdapat outliers
for (col in names(clean_newdata)) {
  if (is.numeric(clean_newdata[[col]])) {
    boxplot(clean_newdata[[col]], main = col)
  }
}



```



## FEATURE SELECTION
```{r}

control = trainControl(method="repeatedcv", number=10, repeats=3)
model = train(LULUS ~ ., data = clean_newdata[, setdiff(names(clean_newdata), "NAMA")], method = "lvq", preProcess = "scale", trControl = control)

# Estimasi Feature yang Penting
importance = varImp(model, scale=FALSE)

# plot importance
plot(importance)

```

## SPLIT DATA
```{r}
# Subset data dengan feature yang dipilih
selected_features <- c("IPK", "RISET", "GRE", "TOEFL", "REKOM_LETTER", "MOT_LETTER", "JENIS_KEL", "USIA")
selected_data <- clean_newdata[, c("LULUS", selected_features)]

# Convert categorical variables to factors
selected_data$JENIS_KEL <- as.factor(selected_data$JENIS_KEL)

# Split the data into training and testing sets
set.seed(123)  # for reproducibility
train_indices <- createDataPartition(selected_data$LULUS, p = 0.8, list = FALSE)
train_data <- selected_data[train_indices, ]
test_data <- selected_data[-train_indices, ]

```


## Model 1 (RF)
```{r}

# Model Training
rf_model <- randomForest(LULUS ~ ., data = train_data)

# Model Prediction on the test set
predictions <- predict(rf_model, newdata = test_data)

# Evaluate the model
conf_matrix <- confusionMatrix(predictions, test_data$LULUS)
accuracy <- conf_matrix$overall["Accuracy"]
precision <- conf_matrix$byClass[["Pos Pred Value"]]

# Display evaluation metrics
print(paste("Accuracy:", accuracy))
print(paste("Precision:", precision))


```

## MODEL 2 (SVM)
```{r}
# Model Training - Support Vector Machine (SVM)
svm_model <- svm(LULUS ~ ., data = train_data)

# Model Prediction on the test set
predictions_svm <- predict(svm_model, newdata = test_data)

# Evaluate the model
conf_matrix_svm <- confusionMatrix(predictions_svm, test_data$LULUS)
accuracy_svm <- conf_matrix_svm$overall["Accuracy"]
precision_svm <- conf_matrix_svm$byClass[["Pos Pred Value"]]

# Display evaluation metrics for SVM
print(paste("SVM Accuracy:", accuracy_svm))
print(paste("SVM Precision:", precision_svm))
```


## Model 3 (LR)
```{r}

# Model Training - Logistics Regression (LR)
lr_model <- glm(LULUS ~ ., data = train_data, family = "binomial")
summary(lr_model)

# Model Prediction on the test set
predictions_lr <- lr_model %>% predict(test_data, type = "response")
predictions_lr

# Convert predicted probabilities to class labels
predicted_classes_lr <- ifelse(predictions_lr > 0.5, "Lulus", "Tidak Lulus")
predicted_classes_lr

# Evaluate the model
conf_matrix_lr <- confusionMatrix(predicted_classes_lr, test_data$LULUS)
accuracy_lr <- conf_matrix_lr$overall["Accuracy"]
precision_lr <- conf_matrix_lr$byClass[["Pos Pred Value"]]

# Display evaluation metrics for LR
print(paste("Logistics Regression  Accuracy:", accuracy_lr))
print(paste("Logistics Regression Precision:", precision_lr))
```

# #shiny sementara
```{r}
ui = fluidPage(
  titlePanel("Judul"),
  sidebarLayout(
    sidebarPanel(
      selectInput('JENIS_KEL', 'Pilih Jenis Kelamin Anda', choices = c('Perempuan', 'Laki-Laki'), 
                  selected = 'Perempuan'),
      sliderInput('USIA', 'Pilih Usia Anda', 
                  min = 1,
                  max = 50,
                  value = 0),
      numericInput('IPK','Masukan IPK Anda : ', value=0),
      numericInput('TOEFL','Masukan Skor TOEFL Anda : ', value=0),
      numericInput('GRE','Masukan Skor Gre Anda : ', value=0),
      numericInput('REKOM_LETTER','Masukan Skor REKOM_LETTER Anda : ', value=0),
      numericInput('MOT_LETTER','Masukan Skor MOT_LETTER Anda : ', value=0),
      selectInput('RISET', 'Apakah Anda Melakukan Riset Sebelumnya', choices = c('Ya', 'Tidak'), 
                  selected = 'Ya'),
      actionButton('hitung', 'Prediksi Kelulusan')
    ), 
    mainPanel(
      textOutput('hasil')
    )
  )
)

server = function(input, output){
  observeEvent(input$hitung, {
    predictions <- predict(model, newdata=data.frame(JENIS_KEL=input$JENIS_KEL, USIA=input$USIA, 
                                                     IPK=input$IPK, TOEFL=input$TOEFL, GRE=input$GRE, 
                                                     REKOM_LETTER=input$REKOM_LETTER, MOT_LETTER=input$MOT_LETTER,
                                                     RISET=input$RISET))
    output$hasil <- renderText({paste('Hasil Prediksi Kelulusan adalah', predictions)})
    })
}

shinyApp(ui=ui, server=server)
```